import SwiftUI

struct DisclaimerView: View {
    @Binding var isPresented: Bool
    @AppStorage("hasAcceptedRisk") private var hasAcceptedRisk = false
    
    var body: some View {
        ZStack {
            Color.black.ignoresSafeArea()
            
            VStack(spacing: 24) {
                Image(systemName: "hand.raised.fill")
                    .font(.system(size: 64))
                    .foregroundStyle(.white)
                
                Text("Hypothetical Performance\nRisk Disclosure")
                    .font(.title.bold())
                    .multilineTextAlignment(.center)
                    .foregroundStyle(.white)
                
                ScrollView {
                    Text("""
                    This application ("SignalVault") is a research tool designed for educational and informational purposes only. It is NOT a financial advisor, broker, or trading platform.

                    1. **No Financial Advice**: The signals, analysis, and data provided by SignalVault are generated by algorithms and should not be construed as investment advice.
                    
                    2. **Hypothetical Performance**: All "Backtest" and "Simulation" results are hypothetical and do not represent actual trading. Past performance is not indicative of future results.
                    
                    3. **Risk of Loss**: Trading in financial markets (Stocks, Options, Crypto) involves significant risk. You can lose your entire investment.
                    
                    4. **System Limitations**: Algorithm inputs (Sentiment, Macro) are based on third-party data which may be inaccurate or delayed.

                    By proceeding, you acknowledge these risks and agree to use SignalVault solely for your own analysis.
                    """)
                    .font(.body)
                    .foregroundStyle(.gray)
                    .multilineTextAlignment(.leading)
                    .padding()
                }
                .frame(maxHeight: 400)
                
                Button(action: {
                    hasAcceptedRisk = true
                    isPresented = false
                }) {
                    Text("I Understand & Accept Risks")
                        .font(.headline)
                        .foregroundStyle(.black)
                        .frame(maxWidth: .infinity)
                        .padding()
                        .background(Color.white)
                        .cornerRadius(12)
                }
            }
            .padding()
        }
    }
}
